steps:
  - id: "yarn-install"
    name: "node:18.17.1"
    entrypoint: yarn
    args:
      - "install"
  - id: migrate
    name: "gcr.io/cloud-builders/yarn"
    entrypoint: sh
    args:
      - "-c"
      - |
        wget https://dl.google.com/cloudsql/cloud_sql_proxy.linux.amd64 -O cloud_sql_proxy
        chmod +x cloud_sql_proxy
        ./cloud_sql_proxy -instances=$$_DB_HOST=tcp:$$_DB_PORT & sleep 3
        export DATABASE_URL=postgresql://$$_DB_USER:$$_DB_PASS@localhost/$$_DB_NAME?schema=public
        yarn workspace api run migrate
    timeout: 1200s
    waitFor:
      - "yarn-install"
  - id: "docker-build"
    timeout: 200s
    name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "-t"
      - "us-central1-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/${_SERVICE_NAME}"
      - "./backend"
  - id: "docker-push"
    name: "gcr.io/cloud-builders/docker"
    args:
      - "push"
      - "us-central1-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/${_SERVICE_NAME}"
    waitFor:
      - "docker-build"
  - id: "deploy-cloud-run"
    name: "gcr.io/cloud-builders/gcloud"
    args:
      - "run"
      - "deploy"
      - "${_SERVICE_NAME}"
      - "--image"
      - "us-central1-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/${_SERVICE_NAME}"
      - "--region"
      - "us-central1"
    waitFor:
      - "docker-push"
options:
  logging: CLOUD_LOGGING_ONLY
substitutions:
  _REPO_NAME: project-management-central
  _SERVICE_NAME: backend
