steps:
  - id: "docker-build"
    timeout: 200s
    name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "-t"
      - "us-central1-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/${_SERVICE_NAME}"
      - "--build-arg"
      - "DATABASE_URL=${_DATABASE_URL}"
      - "--progress=plain"
      - "./backend"
  - id: "docker-push"
    name: "gcr.io/cloud-builders/docker"
    args:
      - "push"
      - "us-central1-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/${_SERVICE_NAME}"
    waitFor:
      - "docker-build"
  - id: "deploy-cloud-run"
    name: "gcr.io/cloud-builders/gcloud"
    args:
      - "run"
      - "deploy"
      - "${_SERVICE_NAME}"
      - "--image"
      - "us-central1-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/${_SERVICE_NAME}"
      - "--region"
      - "us-central1"
    waitFor:
      - "docker-push"
options:
  logging: CLOUD_LOGGING_ONLY
substitutions:
  _REPO_NAME: project-management-central
  _SERVICE_NAME: backend
